# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_travel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelusers', to='travel.User'),
        ),
    ]
